services:
  - type: web
    name: code-detective-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt && pip install -r discord_bot/requirements.txt
    startCommand: cd discord_bot && python main.py & cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: CLONED_REPOS_DIR
        value: ./cloned-repos
      - key: FASTAPI_BASE_URL
        value: http://127.0.0.1:$PORT
      - key: PYTHON_VERSION
        value: "3.11.0"

